version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/GetSign-Temp/jetsign-backend
permissions:
  - object: /var/www/GetSign-Temp/jetsign-backend
    pattern: '**'
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 1000
      runas: root
